### ISSUE TITLE
Структура формы ввода VIN-кода

### ISSUE THREAD

**Issue by avtopro** [vvv-sss/vin_decoder#1]
Для создания форм крайне важно использовать HTML-элемент `<form>`. Это правильно с точки зрения семантики HTML и гораздо удобнее, потому что:
- На десктопе автоматически работает отправка формы по нажатию на Enter (используем не onClick на кнопке, а onSubmit на форме), не надо добавлять клавиатурные обработчики.
- На мобилке могут появляться дополнительные кнопки для отправки формы, зависит от системы.
- Проще настраивать валидацию, автозаполнение и т. п.

См. https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form#the_form_element

Кроме того, важно чтобы у `<input>` был соответствующий его назначению атрибут name, например `name="vin"`, благодаря этому браузер сможет автоматически предложить варианты по автозаполнению поля.

Вместо обработчика onClick на `<input>` для таких целей как отслеживание состояния "активен/неактивен", лучше использовать onFocus. Это более универсальный обработчик, который срабатывает как при клике, так и при активации поля любым другим способом (переходом по Tab, например). Сейчас можно при помощи Tab перейти на текстовое поле и начать вводить VIN, но результат валидации при этом не отобразится как задумано.

https://github.com/vvv-sss/vin_decoder/blob/2dc12b144088288bbf6ded85683124c414bc0611/src/home_page/searchbar.js#L17-L41

**Comment by vvv-sss** [comment]
@avtopro 
> Дякую за ваші issues. Приймаючи до уваги слушні зауваження було зроблене наступне:
- Доданий елемент form, в який момістився input;
- Onclick атрібут з input елементу був прибраний і замінений на onSubmit атрібут для форми;
- До input елемента були додані атрібути name та onFocus з відповідним Event Handler

[SearchBar.js](https://github.com/vvv-sss/vin_decoder/blob/main/src/home_page/searchbar.js)
