### ISSUE TITLE
Подход к управлению состоянием

### ISSUE THREAD

**Issue by avtopro** [vvv-sss/vin_decoder#2]
На примере компонента **SearchBar** разберём некоторые проблемы с управлением состоянием.

https://github.com/vvv-sss/vin_decoder/blob/2dc12b144088288bbf6ded85683124c414bc0611/src/home_page/searchbar.js#L4-L43

Важно различать локальное состояние компонентов и глобальное состояние приложения.

Примерами глобального состояния, от которого зависит логика работы, внешний вид и поведение различных компонентов, в нашем случае может быть:
- "отправленный на расшифровку VIN-код";
- "результат расшифровки VIN-кода";
- "выполняется ли запрос данных" и т. п.

Локальным состоянием будет:
- "текст в поле ввода";
- "результат валидации поля";
- "показ иконки-лоадера в форме" и т. п.

Это, конечно, условное и не единственно верное разделение, но в нём есть своя логика, придерживаясь которой мы получаем более простое и понятное приложение.

Локальное состояние и методы для его изменения никогда не выходят за рамки компонента. Состояние `const [searchIconChange, setSearchIconChange] = useState(SearchIcon)`, отвечающее за иконку-лоадер, вполне может быть таким состоянием, потому что касается только одного конкретного элемента в единственном компоненте SearchBar, но сейчас мы находим что это состояние "размазано" по трём компонентам, включая функцию fetchVinData, которая в принципе не должна ничего "знать" о компонентах.

Более того, состояние searchIconChange логически пересекается с состоянием startFetching — мы ведь "включаем" лоадер когда начинается запрос и "выключаем" спустя 1 секунду после его завершения. В таком случае, searchIconChange является производным от startFetching, а задержку можно реализовать через эффект в SearchBar:

```JavaScript
useEffect(
  () => {
    // Если запрос начался, то сразу включаем лоадер.
    if (startFetching) {
      setSearchIconChange(true);
    }
    // Если запрос завершился, то создаём таймер, который через 1 с выключит лоадер.
    // Не забываем вернуть функцию для удаления таймера, которая позволит избежать
    // наложения эффектов, сработавших с промежутком менее 1 с.
    else {
      const t = window.setTimeout(() => setSearchIconChange(false), 1000);
      return () => {
        window.clearTimeout(t);
      };
    }
  },
  // Выполняется после каждого изменения startFetching.
  [startFetching]
);

```

То же самое касается состояния isInputActive. Его можно хранить внутри SearchBar (все компоненты, зависящие от этого состояния, находятся здесь), и менять через обработчики событий на `<input>`, и через эффект при изменении значений vinNumber и startFetching, от которых оно тоже зависит.

---

**Hint:** желательно делать деструкцию пропсов прямо в определении функционального компонента:

```JavaScript
// Непонятно от чего зависит компонент, надо смотреть в код и выискивать обращения к props.
const SearchBar = (props) => { ... }

// Уже лучше: сразу видно какие данные приходят извне.
const SearchBar = ({ vinNumber, setVinNumber, isInputActive, setIsInputActive, setStartFetching, setSearchIconChange }) => { ... }
```

Ещё лучше — заполнять [PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html).
Совсем хорошо — TypeScript 🙂

**Comment by vvv-sss** [comment]
@avtopro 
> Була зроблена наступна робота:
- Переглянут підхід до управління станами. Глобальними станами залишилися vinNumber, startFetching та vinForSearchHistory які знаходяться в Home Component. 
- Стани isInputActive та searchIconChange перенесені до SearchBar Component та існують як локальні стани
- Команди зі зміною стану SearchIcon відбуваються тільки всередені компоненту SearchBar локально і більше не беребувають поза нього. Використан відповідний хук useEffect для зміни іконки лоадера.
- Зроблена деструкція пропсів у визначенні самої фунцкції або на першій строці всередені фунції усіх компонентів.
