### ISSUE TITLE
Работа с Local Storage

### ISSUE THREAD

**Issue by avtopro** [vvv-sss/vin_decoder#3]
Применение Local Storage для хранения истории запросов само по себе является плюсом.

Вопрос вызывает только подход с сохранением отдельных ключей для каждого из 5 кодов. Преимущества такого решения не ясны, за то есть очевидные недостатки: это по 5 операций чтения-записи, чтобы обновить данные, и много кода. Что если бы требовалось хранить 10, 100 и больше элементов?

https://github.com/vvv-sss/vin_decoder/blob/2dc12b144088288bbf6ded85683124c414bc0611/src/home_page/SearchHistory.js#L5-L15

Гораздо удобнее хранить историю в виде массива, сериализованного в JSON-строку. Порядок элементов при этом сохраняется, требуется только одно чтение и запись данных, а сам код не зависит от количества хранимых элементов.

Функция записи могла бы выглядеть так:

```JavaScript
const saveVinHistory = (vinForSearchHistory) => {
  let vinHistory;

  try {
    // Читаем историю из хранилища.
    vinHistory = JSON.parse(localStorage.getItem('vinHistory'));
  } catch {
    // Ошибка парсинга JSON-строки.
    // Хранилище это незащищённый источник, парсить данные из него нужно с осторожностью.
    // Возможные ошибки обращения к самому Local Storage здесь не учитываем.
  }

  // Добавляем новую запись в историю, сдвигая остальные элементы к концу,
  // и записываем новый массив в хранилище.
  localStorage.setItem(
    'vinHistory',
    JSON.stringify([vinForSearchHistory, ...(vinHistory ?? [])].slice(0, 5))
  );
};

```

**Comment by vvv-sss** [comment]
@avtopro 
> Підхід до збереження історії пошуку був змінений
- Доданий код який формує масив, серіалізований JSON строкою всередені local storage, якщо його ще не існує
- Створені функції для визову масиву історії callVinHistory та збереження нових результатів пошуку в історію saveVinHistory
- З урахуванням вищезгаданних змін зроблені правки коду для рендерингу списку історії на сторінці

[Home.js](https://github.com/vvv-sss/vin_decoder/blob/main/src/home_page/home.js)
[SearchHistory.js](https://github.com/vvv-sss/vin_decoder/blob/main/src/home_page/SearchHistory.js)
