### ISSUE TITLE
Ошибка при прямом обращении к DOM-элементу

### ISSUE THREAD

**Issue by avtopro** [vvv-sss/vin_decoder#4]
Прямое вмешательство в DOM бывает необходимо в редких случаях, но обычно возможностей Реакта бывает достаточно чтобы этого избежать.

В случае с разворачиванием вложенных описаний переменных такой необходимости нет. Правильным подходом было бы создание отдельного Реакт-компонента для вывода `<li>` с информацией о переменной, и с локальным состоянием "свёрнуто/развёрнуто". Клик по элементу должен менять состояние с false на true и наоборот, и в зависимости от состояния должны добавляться необходимые стили. Это стандартный подход.

Как вариант (не самый лучший), можно обойтись и без создания отдельного компонента, а вместо этого в DecodedVinNumberData хранить состояние с массивом ID "развёрнутых" переменных, хотя это и менее наглядно.

https://github.com/vvv-sss/vin_decoder/blob/2dc12b144088288bbf6ded85683124c414bc0611/src/home_page/DecodedVinNumberData.js#L34-L43

Кроме того, что обращение к DOM-элементу через объект события `let objectToBeExpanded = event.target.nextSibling.nextSibling` это не так наглядно, это ещё и приводит к ошибке `DecodedVinNumberData.js:35 Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')`, если кликнуть по стрелочке:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/60243577/216660322-347bf100-40bc-4fa8-bf28-bc0cf5c0fff2.png">

Дело в том, что обработчик onClick добавлен на `<span>`, внутри которого есть `<img>`. Клики по картинке "всплывают" и улавливаются вышестоящим обработчиком, но `event.target` при этом всё равно остаётся элемент `<img>`, т. к. именно на нём произошёл клик. У картинки нет никаких соседних элементов nextSibling, и происходит ошибка.

**Comment by vvv-sss** [comment]
@avtopro 
> Зроблені наступні кроки:
- Створений окремий компонент DecodedList як суб-компонент DecodedVinNumberData
- Вся логіка по роботі з декодованою інформацію перенесено в цей компонент
- Опрацьована функція handleClick та додані змінні в цій функції для кращої читабельності коду
- Зі стрілочної  іконки була знято можливість клікати на неї в CSS стилях, так як саме це і було задумкою на початку

[Parent - DecodedVinNumberData.js](https://github.com/vvv-sss/vin_decoder/blob/main/src/home_page/DecodedVinNumberData.js)
[New Child - DecodedList.js](https://github.com/vvv-sss/vin_decoder/blob/main/src/home_page/DecodedList.js#L2)
